name: cctv_research

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip

  - pip:
      # pytorch GPU
      - torch==2.6.0+cu124
      - torchvision==0.21.0+cu124
      - torchaudio==2.6.0+cu124
      - --extra-index-url https://download.pytorch.org/whl/cu124

      # vision / ML
      - ultralytics==8.4.13
      - opencv-python
      - numpy
      - pillow
      - scipy
      - pandas
      - matplotlib
      - seaborn
      - tqdm
      - PyYAML

      # huggingface
      - transformers==4.44.2
      - tokenizers==0.19.1
      - huggingface_hub
      - safetensors

      # Florence-2
      - timm
      - einops

      # video
      - av
      - decord

      # YOLO
      - thop