name: cctv_qwen

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip

  - pip:
      # pytorch GPU 
      - torch==2.6.0+cu124
      - torchvision==0.21.0+cu124
      - torchaudio==2.6.0+cu124
      - --extra-index-url https://download.pytorch.org/whl/cu124

      # vision / ML 
      - ultralytics==8.4.13
      - opencv-python
      - numpy
      - pillow
      - scipy
      - pandas
      - matplotlib
      - seaborn
      - tqdm
      - PyYAML

      # Qwen 전용 
      - transformers==5.2.0
      - tokenizers==0.22.2
      - accelerate==1.12.0
      - qwen-vl-utils==0.0.14
      - huggingface_hub==1.4.1
      - safetensors

      # vision utils
      - timm
      - einops

      # video 
      - av
      - decord

      # YOLO 
      - thop